'use server';

import { createClient } from '@/lib/supabase/server';
import { revalidatePath } from 'next/cache';
import type { Task, TaskInteraction, Status } from '@/lib/types';
import { createNotification } from './notifications';


async function autoPromoteOverdueTasks() {
  const supabase = await createClient();
  // Fire the high-performance RPC to automatically transition overdue tasks directly in Postgres
  await supabase.rpc('mark_overdue_tasks');
}

export async function getTasks(): Promise<Task[]> {
  // Fire and wait for auto-promotions before returning the board state
  await autoPromoteOverdueTasks();

  const supabase = await createClient();
  const { data, error } = await supabase
    .from('tasks')
    .select(`
      *,
      project:projects ( id, name, status ),
      contact:contacts ( id, name, company, avatar, status ),
      assignee:profiles (*)
    `)
    .order('due_date', { ascending: true, nullsFirst: false });

  if (error) {
    console.error('Error fetching tasks:', error.message || JSON.stringify(error));
    return [];
  }
  return data as Task[];
}

export async function getTaskById(id: string): Promise<Task | null> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('tasks')
    .select(`*, project:projects(*), contact:contacts(*), assignee:profiles(*)`)
    .eq('id', id)
    .single();

  if (error) {
    console.error('Error fetching task:', error);
    return null;
  }
  return data as Task;
}

export async function createTask(taskData: Partial<Task>) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) throw new Error('Unauthenticated');

  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single();
  // Members can now create tasks, so no admin check here

  // Registry number is auto-generated by the database default function

  // Strip any relational fields before inserting
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { id: _id, user_id: _uid, created_at: _ca, updated_at: _ua, project: _p, contact: _c, assignee: _a, ...safeData } = taskData as Task;

  const { data, error } = await supabase
    .from('tasks')
    .insert([{ ...safeData, assigned_to: safeData.assigned_to || user.id, user_id: user.id }])
    .select()
    .single();

  if (error) throw new Error(error.message);

  const newTask = data as Task;
  if (newTask.assigned_to && newTask.assigned_to !== user.id) {
    createNotification({
      userId: newTask.assigned_to,
      actorId: user.id,
      title: 'New Task Assigned',
      message: `You were assigned: ${newTask.title}`,
      type: 'assignment',
      entityType: 'task',
      entityId: newTask.id,
    }).catch(console.error);
  }

  revalidatePath('/tasks');
  revalidatePath('/dashboard');
  return newTask;
}

import { recalculateProjectProgress } from './projects';
import { recordContactInteraction } from './contacts';

export async function updateTask(id: string, updates: Partial<Task>) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Unauthenticated');

  // Keep track of the original task to know if status changed to 'completed'
  // Also needed to verify permissions
  const { data: oldTask } = await supabase.from('tasks').select('status, project_id, contact_id, assigned_to').eq('id', id).single();
  if (!oldTask) throw new Error('Task not found');

  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single();
  if (profile?.role !== 'admin' && oldTask.assigned_to !== user.id) {
    throw new Error('Unauthorized. You can only edit tasks assigned to you.');
  }

  // Strip relational/read-only fields before sending to DB
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { id: _id, user_id: _uid, created_at: _ca, updated_at: _ua, project: _p, contact: _c, assignee: _a, ...safeUpdates } = updates as Task;

  const { data, error } = await supabase
    .from('tasks')
    .update(safeUpdates)
    .eq('id', id)
    .select()
    .single();

  if (error) throw new Error(error.message);

  const taskData = data as Task;

  // Automation Engine: If task just became completed, trigger cascades
  if (oldTask && oldTask.status !== 'completed' && updates.status === 'completed') {
    // 1. Project Progress Recalculation
    const projectId = taskData.project_id || oldTask.project_id;
    if (projectId) {
      // Background trigger, don't await to keep UI fast
      recalculateProjectProgress(projectId).catch(console.error);
    }
    
    // 2. Contact Relationship Update
    const contactId = taskData.contact_id || oldTask.contact_id;
    if (contactId) {
      // Record today as interaction, auto-upgrades to warm if cold/dormant
      recordContactInteraction(contactId).catch(console.error);
    }
  }

  // Hook for assigned_to changes
  if (updates.assigned_to && updates.assigned_to !== oldTask.assigned_to && updates.assigned_to !== user.id) {
    createNotification({
      userId: updates.assigned_to,
      actorId: user.id,
      title: 'Task Reassigned',
      message: `You were assigned: ${taskData.title}`,
      type: 'assignment',
      entityType: 'task',
      entityId: taskData.id,
    }).catch(console.error);
  }

  revalidatePath('/tasks');
  revalidatePath('/dashboard');
  revalidatePath('/kanban');
  return taskData;
}

export async function deleteTask(id: string) {
  const supabase = await createClient();

  // Auth check — defense in depth alongside RLS
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Unauthenticated');

  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single();
  if (profile?.role !== 'admin') throw new Error('Unauthorized. Only admins can delete tasks.');

  const { error } = await supabase
    .from('tasks')
    .delete()
    .eq('id', id); // Admins can delete any task; RLS enforces row visibility

  if (error) throw new Error(error.message);

  revalidatePath('/tasks');
  revalidatePath('/dashboard');
  return true;
}

export async function getTaskInteractions(taskId: string): Promise<TaskInteraction[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('task_interactions')
    .select('*')
    .eq('task_id', taskId)
    .order('created_at', { ascending: true });

  if (error) {
    console.error('Error fetching task interactions:', error);
    return [];
  }
  
  const interactions = data as TaskInteraction[];
  if (interactions.length === 0) return [];

  const userIds = [...new Set(interactions.map(i => i.user_id))];
  const { data: profiles } = await supabase.from('profiles').select('*').in('id', userIds);
  const profileMap = new Map((profiles || []).map(p => [p.id, p]));

  return interactions.map(i => ({
    ...i,
    user: profileMap.get(i.user_id)
  }));
}

export async function addTaskInteraction(taskId: string, content: string): Promise<TaskInteraction> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Unauthenticated');

  const { data, error } = await supabase
    .from('task_interactions')
    .insert([{ task_id: taskId, user_id: user.id, content }])
    .select()
    .single();

  if (error) throw new Error(error.message);
  
  const interaction = data as TaskInteraction;
  const { data: profile } = await supabase.from('profiles').select('*').eq('id', user.id).single();
  if (profile) interaction.user = profile;

  // Notification logic
  const { data: taskData } = await supabase.from('tasks').select('user_id, assigned_to').eq('id', taskId).single();
  if (taskData) {
    // Notify creator
    if (taskData.user_id !== user.id) {
      createNotification({
        userId: taskData.user_id,
        actorId: user.id,
        title: 'New Comment',
        message: 'A comment was left on your task.',
        type: 'comment',
        entityType: 'task',
        entityId: taskId,
      }).catch(console.error);
    }
    // Notify assignee if different from creator and different from commenter
    if (taskData.assigned_to && taskData.assigned_to !== user.id && taskData.assigned_to !== taskData.user_id) {
      createNotification({
        userId: taskData.assigned_to,
        actorId: user.id,
        title: 'New Comment',
        message: 'A comment was left on a task assigned to you.',
        type: 'comment',
        entityType: 'task',
        entityId: taskId,
      }).catch(console.error);
    }
  }

  return data as TaskInteraction;
}

// ─── Stage-Aware Advance Action ──────────────────────────────────────────────

export async function advanceTaskStage(
  taskId: string,
  payload?: { outcome?: 'success' | 'failed' }
): Promise<Task> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Unauthenticated');

  const { data: task } = await supabase
    .from('tasks')
    .select('*')
    .eq('id', taskId)
    .single();
  if (!task) throw new Error('Task not found');

  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single();
  if (profile?.role !== 'admin' && task.assigned_to !== user.id) {
    throw new Error('Unauthorized. You can only advance tasks assigned to you.');
  }

  const jt = (task.job_type ?? '').toLowerCase();
  const current = task.status as Status;
  let next: Status;
  let log: string;

  if (jt === 'delivery') {
    switch (current) {
      case 'pending':     next = 'in-progress'; log = '📦 Rider assigned — pickup confirmed.'; break;
      case 'in-progress': next = 'awaiting';    log = '🚚 Marked out for delivery.'; break;
      case 'awaiting': {
        if (!payload?.outcome) throw new Error('Delivery outcome is required.');
        if (payload.outcome === 'success') {
          next = 'ready'; log = '✅ Delivery successful. Awaiting payment confirmation.';
        } else {
          next = 'failed'; log = '❌ Delivery attempt failed. Ready for retry.';
        }
        break;
      }
      case 'ready':  next = 'completed'; log = '💰 Payment confirmed. Job closed.'; break;
      case 'failed': next = 'awaiting';  log = '🔄 Retry delivery scheduled.'; break;
      default: throw new Error(`Cannot advance Delivery task from status: ${current}`);
    }
  } else if (jt === 'repair') {
    switch (current) {
      case 'pending':     next = 'in-progress'; log = '🔧 Repair started.'; break;
      case 'in-progress': {
        if (!payload?.outcome) throw new Error('Repair outcome is required.');
        if (payload.outcome === 'success') {
          next = 'ready'; log = '✅ Repair complete. Proof attached. Ready for pickup/delivery.';
        } else {
          next = 'failed'; log = '❌ Repair could not be completed. Moved to Failed.';
        }
        break;
      }
      case 'awaiting':    next = 'in-progress'; log = '✅ Customer approval received. Resuming repair.'; break;
      case 'ready':       next = 'completed';   log = '💰 Payment confirmed. Job closed.'; break;
      case 'failed':      next = 'in-progress'; log = '🔄 Repair resumed — back in progress.'; break;
      default: throw new Error(`Cannot advance Repair task from status: ${current}`);
    }
  } else if (jt === 'installation') {
    switch (current) {
      case 'pending':     next = 'in-progress'; log = '🏗️ Installation started.'; break;
      case 'in-progress': {
        if (!payload?.outcome) throw new Error('Installation outcome is required.');
        if (payload.outcome === 'success') {
          next = 'ready'; log = '✅ Installation complete. Proof attached. Awaiting payment.';
        } else {
          next = 'failed'; log = '❌ Installation could not be completed. Moved to Failed.';
        }
        break;
      }
      case 'ready':       next = 'completed';   log = '💰 Payment confirmed. Job closed.'; break;
      case 'failed':      next = 'in-progress'; log = '🔄 Installation restarted — back in progress.'; break;
      default: throw new Error(`Cannot advance Installation task from status: ${current}`);
    }
  } else if (jt === 'maintenance') {
    switch (current) {
      case 'pending':     next = 'in-progress'; log = '🔨 Service started.'; break;
      case 'in-progress': {
        if (!payload?.outcome) throw new Error('Service outcome is required.');
        if (payload.outcome === 'success') {
          next = 'ready'; log = '📋 Service complete. Proof attached. Awaiting payment.';
        } else {
          next = 'failed'; log = '❌ Service could not be completed. Moved to Failed.';
        }
        break;
      }
      case 'ready':       next = 'completed';   log = '💰 Payment confirmed. Job closed.'; break;
      case 'failed':      next = 'in-progress'; log = '🔄 Service retry — back in progress.'; break;
      default: throw new Error(`Cannot advance Maintenance task from status: ${current}`);
    }
  } else if (jt === 'consultation') {
    switch (current) {
      case 'pending':     next = 'in-progress'; log = '💼 Consultation started.'; break;
      case 'in-progress': next = 'ready';       log = '✅ Meeting marked complete.'; break;
      case 'ready':       next = 'completed';   log = '💰 Payment confirmed. Job closed.'; break;
      default: throw new Error(`Cannot advance Consultation task from status: ${current}`);
    }
  } else if (jt === 'development') {
    switch (current) {
      case 'pending':     next = 'in-progress'; log = '💻 Development started.'; break;
      case 'in-progress': next = 'awaiting';    log = '📤 Submitted for client review.'; break;
      case 'awaiting':    next = 'completed';   log = '✅ Client review approved. Job closed.'; break;
      default: throw new Error(`Cannot advance Development task from status: ${current}`);
    }
  } else {
    // Default / Other job types
    switch (current) {
      case 'pending':     next = 'in-progress'; log = '▶️ Work started.'; break;
      case 'in-progress': next = 'ready';       log = '✅ Work complete.'; break;
      case 'ready':       next = 'completed';   log = '✅ Confirmed and closed.'; break;
      default: throw new Error(`Cannot advance task from status: ${current}`);
    }
  }

  const { data: updatedTask, error } = await supabase
    .from('tasks')
    .update({ status: next })
    .eq('id', taskId)
    .select()
    .single();

  if (error) throw new Error(error.message);

  // Auto-log a system interaction for full audit trail
  supabase.from('task_interactions').insert([{
    task_id: taskId,
    user_id: user.id,
    content: `⚡ ${log}`,
  }]).then(() => {}, console.error);

  // Completion cascades
  if (next === 'completed') {
    const projectId = updatedTask.project_id || task.project_id;
    if (projectId) recalculateProjectProgress(projectId).catch(console.error);
    const contactId = updatedTask.contact_id || task.contact_id;
    if (contactId) recordContactInteraction(contactId).catch(console.error);
  }

  revalidatePath('/tasks');
  revalidatePath('/dashboard');
  revalidatePath('/kanban');
  return updatedTask as Task;
}
