'use server';

import { createClient } from '@/lib/supabase/server';
import { revalidatePath } from 'next/cache';
import type { Task, TaskInteraction } from '@/lib/types';
import { createNotification } from './notifications';


async function autoPromoteOverdueTasks() {
  const supabase = await createClient();
  // Fire the high-performance RPC to automatically transition overdue tasks directly in Postgres
  await supabase.rpc('mark_overdue_tasks');
}

export async function getTasks(): Promise<Task[]> {
  // Fire and wait for auto-promotions before returning the board state
  await autoPromoteOverdueTasks();

  const supabase = await createClient();
  const { data, error } = await supabase
    .from('tasks')
    .select(`
      *,
      project:projects ( id, name, status ),
      contact:contacts ( id, name, company, avatar, status ),
      assignee:profiles (*)
    `)
    .order('due_date', { ascending: true, nullsFirst: false });

  if (error) {
    console.error('Error fetching tasks:', error.message || JSON.stringify(error));
    return [];
  }
  return data as Task[];
}

export async function getTaskById(id: string): Promise<Task | null> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('tasks')
    .select(`*, project:projects(*), contact:contacts(*), assignee:profiles(*)`)
    .eq('id', id)
    .single();

  if (error) {
    console.error('Error fetching task:', error);
    return null;
  }
  return data as Task;
}

export async function createTask(taskData: Partial<Task>) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) throw new Error('Unauthenticated');

  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single();
  // Members can now create tasks, so no admin check here

  // Registry number is auto-generated by the database default function

  // Strip any relational fields before inserting
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { id: _id, user_id: _uid, created_at: _ca, updated_at: _ua, project: _p, contact: _c, assignee: _a, ...safeData } = taskData as Task;

  const { data, error } = await supabase
    .from('tasks')
    .insert([{ ...safeData, user_id: user.id }])
    .select()
    .single();

  if (error) throw new Error(error.message);

  const newTask = data as Task;
  if (newTask.assigned_to && newTask.assigned_to !== user.id) {
    createNotification({
      userId: newTask.assigned_to,
      actorId: user.id,
      title: 'New Task Assigned',
      message: `You were assigned: ${newTask.title}`,
      type: 'assignment',
      entityType: 'task',
      entityId: newTask.id,
    }).catch(console.error);
  }

  revalidatePath('/tasks');
  revalidatePath('/dashboard');
  return newTask;
}

import { recalculateProjectProgress } from './projects';
import { recordContactInteraction } from './contacts';

export async function updateTask(id: string, updates: Partial<Task>) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Unauthenticated');

  // Keep track of the original task to know if status changed to 'completed'
  // Also needed to verify permissions
  const { data: oldTask } = await supabase.from('tasks').select('status, project_id, contact_id, assigned_to').eq('id', id).single();
  if (!oldTask) throw new Error('Task not found');

  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single();
  if (profile?.role !== 'admin' && oldTask.assigned_to !== user.id) {
    throw new Error('Unauthorized. You can only edit tasks assigned to you.');
  }

  // Strip relational/read-only fields before sending to DB
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { id: _id, user_id: _uid, created_at: _ca, updated_at: _ua, project: _p, contact: _c, assignee: _a, ...safeUpdates } = updates as Task;

  const { data, error } = await supabase
    .from('tasks')
    .update(safeUpdates)
    .eq('id', id)
    .select()
    .single();

  if (error) throw new Error(error.message);

  const taskData = data as Task;

  // Automation Engine: If task just became completed, trigger cascades
  if (oldTask && oldTask.status !== 'completed' && updates.status === 'completed') {
    // 1. Project Progress Recalculation
    const projectId = taskData.project_id || oldTask.project_id;
    if (projectId) {
      // Background trigger, don't await to keep UI fast
      recalculateProjectProgress(projectId).catch(console.error);
    }
    
    // 2. Contact Relationship Update
    const contactId = taskData.contact_id || oldTask.contact_id;
    if (contactId) {
      // Record today as interaction, auto-upgrades to warm if cold/dormant
      recordContactInteraction(contactId).catch(console.error);
    }
  }

  // Hook for assigned_to changes
  if (updates.assigned_to && updates.assigned_to !== oldTask.assigned_to && updates.assigned_to !== user.id) {
    createNotification({
      userId: updates.assigned_to,
      actorId: user.id,
      title: 'Task Reassigned',
      message: `You were assigned: ${taskData.title}`,
      type: 'assignment',
      entityType: 'task',
      entityId: taskData.id,
    }).catch(console.error);
  }

  revalidatePath('/tasks');
  revalidatePath('/dashboard');
  revalidatePath('/kanban');
  return taskData;
}

export async function deleteTask(id: string) {
  const supabase = await createClient();

  // Auth check — defense in depth alongside RLS
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Unauthenticated');

  const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single();
  if (profile?.role !== 'admin') throw new Error('Unauthorized. Only admins can delete tasks.');

  const { error } = await supabase
    .from('tasks')
    .delete()
    .eq('id', id); // Admins can delete any task; RLS enforces row visibility

  if (error) throw new Error(error.message);

  revalidatePath('/tasks');
  revalidatePath('/dashboard');
  return true;
}

export async function getTaskInteractions(taskId: string): Promise<TaskInteraction[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('task_interactions')
    .select('*, user:profiles(*)')
    .eq('task_id', taskId)
    .order('created_at', { ascending: true });

  if (error) {
    console.error('Error fetching task interactions:', error);
    return [];
  }
  return data as TaskInteraction[];
}

export async function addTaskInteraction(taskId: string, content: string): Promise<TaskInteraction> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Unauthenticated');

  const { data, error } = await supabase
    .from('task_interactions')
    .insert([{ task_id: taskId, user_id: user.id, content }])
    .select('*, user:profiles(*)')
    .single();

  if (error) throw new Error(error.message);

  // Notification logic
  const { data: taskData } = await supabase.from('tasks').select('user_id, assigned_to').eq('id', taskId).single();
  if (taskData) {
    // Notify creator
    if (taskData.user_id !== user.id) {
      createNotification({
        userId: taskData.user_id,
        actorId: user.id,
        title: 'New Comment',
        message: 'A comment was left on your task.',
        type: 'comment',
        entityType: 'task',
        entityId: taskId,
      }).catch(console.error);
    }
    // Notify assignee if different from creator and different from commenter
    if (taskData.assigned_to && taskData.assigned_to !== user.id && taskData.assigned_to !== taskData.user_id) {
      createNotification({
        userId: taskData.assigned_to,
        actorId: user.id,
        title: 'New Comment',
        message: 'A comment was left on a task assigned to you.',
        type: 'comment',
        entityType: 'task',
        entityId: taskId,
      }).catch(console.error);
    }
  }

  return data as TaskInteraction;
}
